<?php

namespace ContainerMij7MjT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MTNQajG.App\Entity\Adress' shared service.
     *
     * @return \App\Entity\Adress
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.MTNQajG": it references class "App\\Entity\\Adress" but no such service exists.');
    }
}
