<?php

namespace ContainerCBXyR4h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MTNQajGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MTNQajG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MTNQajG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'address' => ['privates', '.errored..service_locator.MTNQajG.App\\Entity\\Adress', NULL, 'Cannot autowire service ".service_locator.MTNQajG": it references class "App\\Entity\\Adress" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'address' => 'App\\Entity\\Adress',
            'manager' => '?',
        ]);
    }
}
