<?php

namespace ContainerCBXyR4h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FE7k3Z5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fE7k3Z5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fE7k3Z5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'product' => ['privates', '.errored..service_locator.fE7k3Z5.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.fE7k3Z5": it references class "App\\Entity\\Product" but no such service exists.'],
            'repo' => ['privates', 'App\\Repository\\PictureRepository', 'getPictureRepositoryService', true],
        ], [
            'manager' => '?',
            'product' => 'App\\Entity\\Product',
            'repo' => 'App\\Repository\\PictureRepository',
        ]);
    }
}
