<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCBXyR4h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCBXyR4h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCBXyR4h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCBXyR4h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCBXyR4h\App_KernelDevDebugContainer([
    'container.build_hash' => 'CBXyR4h',
    'container.build_id' => '0c762290',
    'container.build_time' => 1649511589,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCBXyR4h');
