<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container05r5ZKx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container05r5ZKx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container05r5ZKx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container05r5ZKx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container05r5ZKx\App_KernelDevDebugContainer([
    'container.build_hash' => '05r5ZKx',
    'container.build_id' => 'a82de585',
    'container.build_time' => 1649581697,
], __DIR__.\DIRECTORY_SEPARATOR.'Container05r5ZKx');
